# Generated by Django 5.1.1 on 2024-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_reserva_numero_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('accommodation_quote', 'accommodation_quote'), ('event_quote', 'event_quote'), ('lost_object', 'lost_object'), ('general_question', 'general_question'), ('complaint', 'complaint'), ('accommodation_reservation', 'accommodation_reservation'), ('event_reservation', 'event_reservation'), ('special_request', 'special_request')], default='accommodation_quote', max_length=100),
        ),
    ]
